### ISSUE TITLE
error G4127D1E8: The getter 'StrokeAlign' isn't defined for the class '_FocusedContainer'

### ISSUE THREAD

**Issue by TheValkDokk** [bosskmk/pluto_layout#2]
Got these 2 error even after i create new project. i dont have another pc to test so this may only me but can you investigate?

`/C:/Users/ValkDokk/AppData/Local/Pub/Cache/hosted/pub.dev/pluto_layout-0.3.0/lib/src/ui/pluto_layout_container.dart(142,30): error G4127D1E8: The getter 'StrokeAlign' isn't defined for the class '_FocusedContainer'. [C:\Projects\flame_demo\build\windows\flutter\flutter_assemble.vcxproj]

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Projects\flame_demo\build\windows\CMakeFiles\abbd1966738140111e8175bf1a2bb3aa\flutter_windows.dll.rule;C:\Projects\flame_demo\build\windows\CMakeFiles\0dfc9ba6e9d86f9ffbdb465a6b13bc3d\flutter_assemble.rule' exited with code 1. [C:\Projects\flame_demo\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.`

**Comment by TheValkDokk** [comment]
my setting: 
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

**Comment by bosskmk** [comment]
The problem does not occur in 3.3.9.
Perhaps your flutter version is not 3.3.x.

Below is the problem with version 3.5.x.
This is planned to be fixed when updated to stable.
https://github.com/bosskmk/pluto_layout/issues/1
